Upgrade directus in all examples
directus/examples pull request #99
Opened 2022-05-19 06:32 UTC by avioli

I've upgraded `directus` across the board to `9.10.0` in all the examples and enabled [CORS](https://docs.directus.io/configuration/config-options/#cors) which uses `CORS=true` to match the Origin header.

Some examples like `nuxt` use an indirect package - `nuxt-directus`, which I upgraded to their latest versions as well.

2022-05-19 07:16 UTC, azrikahar requested changes
First of all, thank you very much for the upgrades across the board!

Quick question, was this verified with the current directus example? Since the database is still technically on `9.5.0` if I recall correctly as it has yet to run through any migrations since then. Haven't really got the chance to test this out locally, so once again thanks for the much needed maintenance. 👍

2022-05-21 07:28 UTC, Intevel submitted a review, later dismissed
I wouldn't update the Nuxt 3 like that, it's from a guide. We have to update the guide then too.

2022-05-21 07:28 UTC, Intevel commented on nuxt3/nuxt3-directus-blog/package.json
> +    "dev": "nuxt dev",
It's called "nuxi" not "nuxt" the new CLI tool for Nuxt 3

2022-05-21 07:28 UTC, Intevel commented on nuxt3/nuxt3-directus-blog/pages/index.vue
> +const posts = await getItems({ collection: "articles" });
Take a look at the comment.

2022-05-23 00:07 UTC, avioli commented
> Quick question, was this verified with the current directus example?

@azrikahar Where is the current directus example?

I simply saw this repo in the org, cloned it on my M1 and nothing worked, so I got to fix it. When it turned out it is not a huge change-set I decided to fork and send a PR.

2022-05-23 00:11 UTC, avioli commented on nuxt3/nuxt3-directus-blog/package.json
> +    "dev": "nuxt dev",
When I setup a new project with nuxt3, following their [Getting started guide](https://v3.nuxtjs.org/getting-started/quick-start#new-project) - the generated code doesn't use `nuxi`, but `nuxt` (although the project setup does use the former - `npx nuxi init nuxt-app`).

<img width="300" alt="Screen Shot 2022-05-23 at 10 10 39 am" src="https://user-images.githubusercontent.com/524259/169722308-90b3202a-281c-4167-97e2-73b68d1f77b7.png">

2022-05-23 00:13 UTC, avioli commented on nuxt3/nuxt3-directus-blog/pages/index.vue
> +const posts = await getItems({ collection: "articles" });
Sorry, but which comment?

2022-05-23 00:22 UTC, avioli commented on nuxt3/nuxt3-directus-blog/nuxt.config.ts
> +		url: "http://localhost:8055/",
I figured, since the `nuxt3` example does look entirely out of place. I tried to make it work anyways (with the least number of changes). Let me know and I'll revert the commit.

2022-05-23 00:30 UTC, avioli commented on nuxt3/nuxt3-directus-blog/nuxt.config.ts
> +		url: "http://localhost:8055/",
Or not revert, but keep the collection and property names as per the guide, but then submit a PR for the guides repo to update the [markup](https://github.com/directus/guides/blob/main/get-started-building-a-nuxt-3-blog-with-directus/index.md#you-are-ready-to-code-)

2022-05-23 00:33 UTC, avioli commented on nuxt3/nuxt3-directus-blog/package.json
> +    "dev": "nuxt dev",
Having said that - reverting to using `nuxi` still works, so I'll do just that.

2022-05-23 02:15 UTC, azrikahar commented
> @azrikahar Where is the current directus example? Is it https://github.com/directus/guides
> 
> I simply saw this repo in the org, cloned it on my M1 and nothing worked, so I got to fix it. When it turned out it is not a huge change-set I decided to fork and send a PR.

It is in this repo, `/directus` directory/folder ([link](https://github.com/directus/examples/tree/main/directus)). Just to clarify, when you say "nothing worked", did you run this directus example first before trying out the other examples (except nuxt3)? It should be described as a prerequisite in all of their README files, but do let us know if it isn't.

2022-05-23 02:22 UTC, azrikahar commented on nuxt3/nuxt3-directus-blog/nuxt.config.ts
> +		url: "http://localhost:8055/",
Another alternative approach would be to split out the nuxt3 changes on another PR (depending on the decision made), and keep this PR purely on actual upgrades. 👍

2022-05-23 02:29 UTC, avioli commented
> Just to clarify, when you say "nothing worked", did you run this directus example first before trying out the other examples (except nuxt3)?

I did run the directus example first, but the `npm install` command failed on my M1 Macbook, since it was trying to compile some node-gyp native binary, so I upgraded to latest directus and `npm install`-ed again, which completed successfully.

<details>
  <summary> `npm install` output </summary>

```sh
/private/tmp/examples/directus> npm i
npm WARN deprecated @types/pino@7.0.5: This is a stub types definition. pino provides its own type definitions, so you do not need this installed.
npm WARN deprecated @types/cssnano@5.1.0: This is a stub types definition. cssnano provides its own type definitions, so you do not need this installed.
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated querystring@0.2.0: The querystring API is considered Legacy. new code should use the URLSearchParams API instead.
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated uuid@3.3.2: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated node-pre-gyp@0.11.0: Please upgrade to @mapbox/node-pre-gyp: the non-scoped node-pre-gyp package is deprecated and only the @mapbox scoped package will recieve updates in the future
npm WARN deprecated tar@2.2.2: This version of tar is no longer supported, and will not receive security updates. Please upgrade asap.
npm ERR! code 1
npm ERR! path /private/tmp/examples/directus/node_modules/sqlite3
npm ERR! command failed
npm ERR! command sh -c node-pre-gyp install --fallback-to-build
npm ERR! CC(target) Release/obj.target/nothing/node_modules/node-addon-api/nothing.o
npm ERR!   LIBTOOL-STATIC Release/nothing.a
npm ERR!   ACTION deps_sqlite3_gyp_action_before_build_target_unpack_sqlite_dep Release/obj/gen/sqlite-autoconf-3340000/sqlite3.c
npm ERR! Failed to execute '/Users/avioli/.nodenv/versions/16.13.0/bin/node /Users/avioli/.nodenv/versions/16.13.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/private/tmp/examples/directus/node_modules/sqlite3/lib/binding/napi-v3-darwin-arm64/node_sqlite3.node --module_name=node_sqlite3 --module_path=/private/tmp/examples/directus/node_modules/sqlite3/lib/binding/napi-v3-darwin-arm64 --napi_version=8 --node_abi_napi=napi --napi_build_version=3 --node_napi_label=napi-v3' (1)
npm ERR! node-pre-gyp info it worked if it ends with ok
npm ERR! node-pre-gyp info using node-pre-gyp@1.0.8
npm ERR! node-pre-gyp info using node@16.13.0 | darwin | arm64
npm ERR! node-pre-gyp info check checked for "/private/tmp/examples/directus/node_modules/sqlite3/lib/binding/napi-v3-darwin-arm64/node_sqlite3.node" (not found)
npm ERR! node-pre-gyp http GET https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v5.0.2/napi-v3-darwin-arm64.tar.gz
npm ERR! node-pre-gyp ERR! install response status 403 Forbidden on https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v5.0.2/napi-v3-darwin-arm64.tar.gz 
npm ERR! node-pre-gyp WARN Pre-built binaries not installable for sqlite3@5.0.2 and node@16.13.0 (node-v93 ABI, unknown) (falling back to source compile with node-gyp) 
npm ERR! node-pre-gyp WARN Hit error response status 403 Forbidden on https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v5.0.2/napi-v3-darwin-arm64.tar.gz 
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@8.2.0
npm ERR! gyp info using node@16.13.0 | darwin | arm64
npm ERR! gyp info ok 
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@8.2.0
npm ERR! gyp info using node@16.13.0 | darwin | arm64
npm ERR! gyp info find Python using Python version 3.9.13 found at "/opt/homebrew/opt/python@3.9/bin/python3.9"
npm ERR! gyp info spawn /opt/homebrew/opt/python@3.9/bin/python3.9
npm ERR! gyp info spawn args [
npm ERR! gyp info spawn args   '/Users/avioli/.nodenv/versions/16.13.0/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
npm ERR! gyp info spawn args   'binding.gyp',
npm ERR! gyp info spawn args   '-f',
npm ERR! gyp info spawn args   'make',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/private/tmp/examples/directus/node_modules/sqlite3/build/config.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/Users/avioli/.nodenv/versions/16.13.0/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/Users/avioli/Library/Caches/node-gyp/16.13.0/include/node/common.gypi',
npm ERR! gyp info spawn args   '-Dlibrary=shared_library',
npm ERR! gyp info spawn args   '-Dvisibility=default',
npm ERR! gyp info spawn args   '-Dnode_root_dir=/Users/avioli/Library/Caches/node-gyp/16.13.0',
npm ERR! gyp info spawn args   '-Dnode_gyp_dir=/Users/avioli/.nodenv/versions/16.13.0/lib/node_modules/npm/node_modules/node-gyp',
npm ERR! gyp info spawn args   '-Dnode_lib_file=/Users/avioli/Library/Caches/node-gyp/16.13.0/<(target_arch)/node.lib',
npm ERR! gyp info spawn args   '-Dmodule_root_dir=/private/tmp/examples/directus/node_modules/sqlite3',
npm ERR! gyp info spawn args   '-Dnode_engine=v8',
npm ERR! gyp info spawn args   '--depth=.',
npm ERR! gyp info spawn args   '--no-parallel',
npm ERR! gyp info spawn args   '--generator-output',
npm ERR! gyp info spawn args   'build',
npm ERR! gyp info spawn args   '-Goutput_dir=.'
npm ERR! gyp info spawn args ]
npm ERR! gyp info ok 
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@8.2.0
npm ERR! gyp info using node@16.13.0 | darwin | arm64
npm ERR! gyp info spawn make
npm ERR! gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
npm ERR! warning: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool: archive library: Release/nothing.a the table of contents is empty (no object file members in the library define global symbols)
npm ERR! /bin/sh: python: command not found
npm ERR! make: *** [Release/obj/gen/sqlite-autoconf-3340000/sqlite3.c] Error 127
npm ERR! gyp ERR! build error 
npm ERR! gyp ERR! stack Error: `make` failed with exit code: 2
npm ERR! gyp ERR! stack     at ChildProcess.onExit (/Users/avioli/.nodenv/versions/16.13.0/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
npm ERR! gyp ERR! stack     at ChildProcess.emit (node:events:390:28)
npm ERR! gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:290:12)
npm ERR! gyp ERR! System Darwin 21.4.0
npm ERR! gyp ERR! command "/Users/avioli/.nodenv/versions/16.13.0/bin/node" "/Users/avioli/.nodenv/versions/16.13.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/private/tmp/examples/directus/node_modules/sqlite3/lib/binding/napi-v3-darwin-arm64/node_sqlite3.node" "--module_name=node_sqlite3" "--module_path=/private/tmp/examples/directus/node_modules/sqlite3/lib/binding/napi-v3-darwin-arm64" "--napi_version=8" "--node_abi_napi=napi" "--napi_build_version=3" "--node_napi_label=napi-v3"
npm ERR! gyp ERR! cwd /private/tmp/examples/directus/node_modules/sqlite3
npm ERR! gyp ERR! node -v v16.13.0
npm ERR! gyp ERR! node-gyp -v v8.2.0
npm ERR! gyp ERR! not ok 
npm ERR! node-pre-gyp ERR! build error 
npm ERR! node-pre-gyp ERR! stack Error: Failed to execute '/Users/avioli/.nodenv/versions/16.13.0/bin/node /Users/avioli/.nodenv/versions/16.13.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/private/tmp/examples/directus/node_m [...]

2022-05-23 04:37 UTC, azrikahar commented
Hmm judging from the error message: `Pre-built binaries not installable for sqlite3@5.0.2 and node@16.13.0`, I believe this is technically an issue with sqlite3, though I do wonder why is it looking for `5.0.2` when the notation is `^5.0.2` instead.. Likely very similar issue to https://github.com/TryGhost/node-sqlite3/issues/1538, where the most recent reply is indeed asking to use a later version.

When you updated all these examples to 9.10.0, it's resolved due to https://github.com/directus/directus/pull/13051, where we upgraded Knex to v2 and consequently set sqlite3 to at least `5.0.6`, which should be the reason why it worked for you. So yeah, more of a sqlite3 thing rather than directus tbh, but the examples are still due for an upgrade nonetheless so all good.

2022-05-24 01:54 UTC, avioli commented on nuxt3/nuxt3-directus-blog/nuxt.config.ts
> +		url: "http://localhost:8055/",
Ok. I'll revert all nuxt3 changes and put them into another PR.

2022-05-24 02:05 UTC, avioli commented
Refactored nuxt3 upgrade into #100, but reverted all other changes so the guide doesn't have to change.

2022-06-08 06:34 UTC, merged

2022-06-08 06:34 UTC, azrikahar commented
Thanks again @avioli!